## ============================================================================
## maclc.xdc — the core's own constraints (the framework build picks up every
## .xdc under rtl/). FIRST PASS, written before any Vivado run: after the first
## build, check the timing summary and the "IO Register" column of the I/O
## report (report_io), and fix anything below that Vivado warns about.
##
## Cell paths are matched loosely (*/mac/...) because the framework's wrapper
## hierarchy names are generated by Chisel. Port names are the framework's
## (verilog/handheld/rev_4.xdc).
## ============================================================================

## ---- CPU: two-cycle paths ---------------------------------------------------
## The TG68K kernel only advances on its clock enable (every other clk_sys),
## so register-to-register paths inside it have two clk_sys periods. MiSTer's
## MacLC.sdc grants the same credit (see the 2026-09-15 TG68 kernel commit).
set_multicycle_path -setup -end 2 \
	-from [get_cells -quiet -hier -filter {NAME =~ */mac/tg68k/tg68k/* && IS_SEQUENTIAL}] \
	-to   [get_cells -quiet -hier -filter {NAME =~ */mac/tg68k/tg68k/* && IS_SEQUENTIAL}]
set_multicycle_path -hold -end 1 \
	-from [get_cells -quiet -hier -filter {NAME =~ */mac/tg68k/tg68k/* && IS_SEQUENTIAL}] \
	-to   [get_cells -quiet -hier -filter {NAME =~ */mac/tg68k/tg68k/* && IS_SEQUENTIAL}]

## Peripheral read data is only consumed by the E-paced VPA cycle, >= 5 clk_sys
## after it settles (see maclc_core.sv / MacLC.sv periph_din_reg).
set_multicycle_path -setup -end 2 -to [get_cells -quiet -hier -filter {NAME =~ */mac/periph_din_reg_reg*}]
set_multicycle_path -hold  -end 1 -to [get_cells -quiet -hier -filter {NAME =~ */mac/periph_din_reg_reg*}]

## ---- SDRAM (W9825G6KH-6) -------------------------------------------------------
## The SDRAM clock is clk_mem inverted by an ODDR (sdram.sv sdramclk_ddr): the
## chip samples commands half a clk_mem period after the controller launches
## them, and the controller captures DQ on clk_mem's falling edge, one full
## period after the chip launched it (CAS latency 2). Same scheme and numbers
## as MiSTer's MacLC.sdc, which measured +2.2 ns setup on Cyclone V.
create_generated_clock -name sdram_clk -divide_by 1 -invert \
	-source [get_pins -quiet -of_objects [get_cells -quiet -hier -filter {NAME =~ */mac/sdram/sdramclk_ddr}] -filter {REF_PIN_NAME == C}] \
	[get_ports sdram_clk]

## DQ valid tAC (<= 6 ns at CL2) after the chip clock, held tOH (>= 3 ns).
set_input_delay  -clock sdram_clk -max 6.5 [get_ports {sdram_dq[*]}]
set_input_delay  -clock sdram_clk -min 2.5 [get_ports {sdram_dq[*]}]
## Command/address/data setup tIS 1.5 ns, hold tIH 0.8 ns, plus board skew.
set_output_delay -clock sdram_clk -max  2.0 [get_ports {sdram_a[*] sdram_bs[*] sdram_dq[*] sdram_ldqm sdram_udqm sdram_cas_n sdram_ras_n sdram_we_n sdram_cs_n[0]}]
set_output_delay -clock sdram_clk -min -0.8 [get_ports {sdram_a[*] sdram_bs[*] sdram_dq[*] sdram_ldqm sdram_udqm sdram_cas_n sdram_ras_n sdram_we_n sdram_cs_n[0]}]

## Registers in the I/O blocks: their pin timing then cannot change with
## placement — the lesson of rtl/maclc/sdram.sv's 2026-09-12 read-capture note.
## (sd_addr also drives DQM and sd_data_oe fans out to 16 pins, so those two
## stay in the fabric.)
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */mac/sdram/sd_data_q_reg*}]
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */mac/sdram/sd_data_reg*}]
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */mac/sdram/sd_cmd_reg*}]
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */mac/sdram/sd_ba_reg*}]

## ---- SRAM (IS61WV25616, 10 ns) as VRAM -----------------------------------------
## gb_vram_sram drives every pin from a register and captures read data one
## full clk_sys period (30.8 ns) after the address leaves; tAA is 10 ns, so
## the budget is generous. Pack them so it stays that way.
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */vram/sram_a_reg*}]
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */vram/sram_we_n_reg*}]
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */vram/sram_oe_n_reg*}]
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */vram/sram_ce_n_reg*}]
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */vram/sram_mask_n_reg*}]
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */vram/sram_dq_out_reg*}]
set_property IOB TRUE [get_cells -quiet -hier -filter {NAME =~ */vram/rd_data_reg*}]
